name: p4env37
channels:
  - psi4/label/dev
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - psi4
  - dftd3
  - ipywidgets
  - seaborn
  - pygments
  - matplotlib
  - scipy
  - sympy
  - pandas
  - altair
  - tqdm
  - yapf
  - "pip>=19"
  - pip:
    - qiskit
    - pyscf
